name:  Manual .NET Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  print-runtime-context:
    runs-on:  ubuntu-latest

    steps:
      - name: 🔔 Start build process...
        run: echo "Build process has started"
    
  
